kind: Service
apiVersion: v1
metadata:
  name: mydevops
  labels:
    app: mydevops
spec:
  ports:
    - port: 8080        #Exposed container port
      targetPort: 80    #Pods port
      nodePort: 31200
  selector:
    app: mydevops       #Apply this service to any pods which has the specified label
  type: LoadBalancer    #Specifies the service type i.e ClusterIP or NodePortS